### ISSUE TITLE
IndexedDB regression in WebWorkers

### ISSUE THREAD

**Issue by billiegoose** [jvilk/BrowserFS#231]
It may take me a while to get to the bottom of this; I've got a WebWorker that works fine with version 1.4.3: 

```js
importScripts('https://unpkg.com/browserfs@1.4.3/dist/browserfs.js')
BrowserFS.configure({
  fs: "IndexedDB",
  options: { }
}, (err) => ......
```

but silently fails to write files or create directories in version 2.0.0:

```js
importScripts('https://unpkg.com/browserfs@2.0.0/dist/browserfs.js')
BrowserFS.configure({
  fs: "IndexedDB",
  options: { }
}, (err) => ......
```

**Comment by jvilk** [comment]
Oh, that's odd! I'll take a look when I have some free cycles.

btw, is the 2.0 code using a fresh database, or a version created with 1.4.3? (either design should work)

**Comment by isysd** [comment]
@wmhilton would you share the project that this webworker is operating in? I'm having trouble getting the web workers to work with IndexedDB even from 1.4.3.

**Comment by jcubic** [comment]
Not sure if this is the same, but I got error
```
Error: ENOENT: No such file or directory., '/'
Error
    at new ApiError (https://cdn.jsdelivr.net/npm/browserfs@2.x.x/dist/browserfs.js:5430:22)
    at Function.FileError (https://cdn.jsdelivr.net/npm/browserfs@2.x.x/dist/browserfs.js:5455:16)
    at Function.ENOENT (https://cdn.jsdelivr.net/npm/browserfs@2.x.x/dist/browserfs.js:5458:21)
    at https://cdn.jsdelivr.net/npm/browserfs@2.x.x/dist/browserfs.js:13987:37
    at IDBRequest. (https://cdn.jsdelivr.net/npm/browserfs@2.x.x/dist/browserfs.js:14270:17)
```

When calling `fs.readdir('/')` inside service worker, outside everything works fine, I Have recursive function that list all the files with meta data, it work without problems in normal code.

It's been 2 years since this bug was created same as last commit, is this project maintained?

**Comment by dr-vortex** [comment]
Closing (stale). If you would like to reopen this issue, please do so by creating a new issue in the relevant repositories of @browser-fs
