### ISSUE TITLE
Overlaying FolderAdapter bug: stat.clone is not a function

### ISSUE THREAD

**Issue by trenta3** [jvilk/BrowserFS#264]
I'm running FolderAdapter with default node fs module.
The problem is with running FolderAdapter with the fs module as readable part of an Overlay and reading an existant directory that is not the root.

Using BrowserFS 1.4.3 from npm repos.

MWE:
```node
// Working code: execution logs ['afile']
const BrowserFS = require('browserfs')

BrowserFS.configure({
    fs: "FolderAdapter",
    options: {
	folder: "./",
	wrapped: require('fs')
    }
}, async (err) => {
    if (err)
	throw err;

    var fs = BrowserFS.BFSRequire('fs')
    fs.readdir("/dist/", (err, files) => {
	if (err) throw err
	console.log(files)
    })
})
```

```node
// Non working code, see below for the exception
const BrowserFS = require('browserfs')

BrowserFS.configure({
    fs: "OverlayFS",
    options: {
	readable: {
	    fs: "FolderAdapter",
	    options: {
		folder: "./",
		wrapped: require('fs')
	    }
	},
	writable: {
	    fs: "InMemory"
	}
    }
}, async (err) => {
    if (err)
	throw err;

    var fs = BrowserFS.BFSRequire('fs')
    fs.readdir("/dist/", (err, files) => {
	if (err) throw err
	console.log(files)
    })
})
```

The exception it gives is:
```
PROJECT/node_modules/browserfs/dist/browserfs.js:10974
	                        stat = stat.clone();
	                                    ^

TypeError: stat.clone is not a function
    at PROJECT/node_modules/browserfs/dist/browserfs.js:10974:38
    at PROJECT/node_modules/browserfs/dist/browserfs.js:7633:17
    at FSReqWrap.oncomplete (fs.js:153:5)

```

**Comment by jvilk** [comment]
We don't support wrapping the node file system module like that. The `wrapper` argument must be a BrowserFS file system backend. Currently, there's no Node file system backend.
